[package]
name = "doseid-macros"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2.0", features = ["full"] }
