name: doseid

on:
  push:
    tags:
      - '*'

concurrency:
  group: doseid-${{ github.ref }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    outputs:
      amd64-digest: ${{ steps.export-amd64.outputs.digest }}
      arm64-digest: ${{ steps.export-arm64.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=doseidotio/doseid,push-by-digest=true,name-canonical=true
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}

      - name: Export digest (AMD64)
        if: matrix.platform == 'linux/amd64'
        id: export-amd64
        run: |
          echo "digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

      - name: Export digest (ARM64)
        if: matrix.platform == 'linux/arm64'
        id: export-arm64
        run: |
          echo "digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create -t doseidotio/doseid \
            ${{ needs.build.outputs.amd64-digest }} \
            ${{ needs.build.outputs.arm64-digest }}
          
          docker buildx imagetools create -t doseidotio/doseid:${{ github.sha }} \
            ${{ needs.build.outputs.amd64-digest }} \
            ${{ needs.build.outputs.arm64-digest }}
          
          docker buildx imagetools create -t doseidotio/doseid:${{ env.VERSION }} \
            ${{ needs.build.outputs.amd64-digest }} \
            ${{ needs.build.outputs.arm64-digest }}
