name: macos

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dsherret/rust-toolchain-file@v1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Install x86_64-apple-darwin
        run: rustup target add x86_64-apple-darwin

      - name: Build macOS Rust
        run: ./scripts/macos_rust_build.sh

      - name: macOS Release
        run: ./scripts/macos_release.sh

      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: Dosei.dmg
          path: target/Dosei.dmg

#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          pattern: Dosei.dmg
#          merge-multiple: true
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            Dosei.dmg
