name: macos

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dsherret/rust-toolchain-file@v1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Build macOS Rust
        run: ./scripts/macos_rust_build.sh

      - name: macOS Release
        run: ./scripts/macos_release.sh

#      - name: Zip
#        run: zip -j sm-${{ matrix.target }}.zip target/${{ matrix.target }}/release/sm
#
#      - name: Upload Zip
#        uses: actions/upload-artifact@v4
#        with:
#          name: sm-${{ matrix.target }}
#          path: sm-${{ matrix.target }}.zip
#
#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          pattern: sm-*
#          merge-multiple: true
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            sm-x86_64-unknown-linux-gnu.zip
#            sm-aarch64-unknown-linux-gnu.zip
#            sm-x86_64-apple-darwin.zip
#            sm-aarch64-apple-darwin.zip
